import {NextResponse} from 'next/server';
import {z} from 'zod';
import {prisma} from '@/lib/db';
import {getActor,AppError,jsonSafe,requirePermission,audit,scope} from '@/lib/access';
import {readResource,movementScope,employeeScope,clearCache} from '@/lib/read-service';
import {writeResource} from '@/lib/write-service';
import {storeFile,fileUrl} from '@/lib/storage';
import {receiptPdf,tablePdf,labelsPdf} from '@/lib/pdf-service';
export const dynamic='force-dynamic';
const output=(data:unknown)=>NextResponse.json(jsonSafe(data));
const pdfResponse=(buffer:Buffer,name:string,download=false)=>new Response(new Uint8Array(buffer),{headers:{'Content-Type':'application/pdf','Content-Disposition':`${download?'attachment':'inline'}; filename="${name}"`,'Cache-Control':'private, no-store'}});
function failure(e:any){console.error('Solicitud rechazada:',e?.message);if(e instanceof AppError)return NextResponse.json({error:{mensaje:e.message,detalles:e.details}},{status:e.status});if(e instanceof z.ZodError)return NextResponse.json({error:{mensaje:'Revisa los campos del formulario.',detalles:e.issues.map((i:any)=>`${i.path.join('.')}: ${i.message}`)}},{status:422});if(e?.code==='P2002')return NextResponse.json({error:{mensaje:'Ese código, correo o número de empleado ya existe.'}},{status:409});return NextResponse.json({error:{mensaje:'No pudimos guardar la operación. Intenta de nuevo.'}},{status:500});}
export async function GET(request:Request,{params}:{params:Promise<{path:string[]}>}){try{const {path}=await params;const a=await getActor();const url=new URL(request.url);const [resource,id,action]=path;
 if(resource==='borradores'&&id&&action==='pdf'){const d=await prisma.borradorEntrega.findFirst({where:{id,usuarioId:a.id}});if(!d)throw new AppError(404,'Comprobante no encontrado.');return pdfResponse(await receiptPdf(d.folio,d.datos,d.creadoEn),`${d.folio}.pdf`,url.searchParams.get('download')==='1');}
 if(resource==='movimientos'&&id&&(action==='pdf'||action==='evidencia')){requirePermission(a,'documentos.ver');const m=await prisma.movimiento.findFirst({where:{id,...movementScope(a)},include:{detalles:true}});if(!m)throw new AppError(404,'Comprobante no encontrado.');await audit(a,'DESCARGAR','Movimiento',id);if(action==='evidencia'){const file=await prisma.archivo.findUnique({where:{cloud_storage_path:m.evidenciaFirmaPdf??'none'}});if(!file)throw new AppError(404,'Este movimiento histórico no tiene evidencia firmada.');return NextResponse.redirect(await fileUrl(file,url.searchParams.get('download')==='1'));}if(m.comprobanteArchivoId){const file=await prisma.archivo.findUniqueOrThrow({where:{id:m.comprobanteArchivoId}});return NextResponse.redirect(await fileUrl(file,url.searchParams.get('download')==='1'));}if(m.tipo==='ENTREGA')return pdfResponse(await receiptPdf(m.folio,{...m,renglones:m.detalles},m.fecha),`${m.folio}.pdf`,url.searchParams.get('download')==='1');const arts=await prisma.articulo.findMany({where:{id:{in:m.detalles.map((d:any)=>d.articuloId)}}});return pdfResponse(await tablePdf(`${m.tipo} · ${m.folio}`,['Artículo','Cantidad','Estado','Saldo'],m.detalles.map((d:any)=>[arts.find((art:any)=>art.id===d.articuloId)?.nombre,d.cantidad,d.estadoRetorno??d.estadoSalida??'Registrado',d.saldoAlmacenDespues])),`${m.folio}.pdf`,url.searchParams.get('download')==='1');}
 if(resource==='archivos'&&id){const f=await prisma.archivo.findUniqueOrThrow({where:{id}});if(f.usuarioId!==a.id){const related=await prisma.movimiento.findFirst({where:{...movementScope(a),OR:[{fotoArticuloId:id},{firmaArchivoId:id},{comprobanteArchivoId:id},{evidenciaFirmaPdf:f.cloud_storage_path}]}});if(!related)throw new AppError(403,'No tienes permiso para ver este archivo.');}return NextResponse.redirect(await fileUrl(f,url.searchParams.get('download')==='1'));}
 if(resource==='etiquetas'){requirePermission(a,'etiquetas.imprimir');const ids=(url.searchParams.get('ids')??'').split(',').slice(0,30);const type=url.searchParams.get('type')??'articulos';let items:any[]=[];if(type==='empleados'){const es=await prisma.empleado.findMany({where:{id:{in:ids},...employeeScope(a)}});items=es.map((e:any)=>({name:`${e.nombre} ${e.apellidoPaterno}`,code:e.numeroEmpleado,payload:e.gafeteQR}));}else if(type==='piezas'){const ps=await prisma.pieza.findMany({where:{id:{in:ids}},include:{articulo:true}});for(const p of ps)scope(a,p.almacenId??'');items=ps.map((p:any)=>({name:p.articulo.nombre,code:p.codigoInterno,payload:p.codigoQR}));}else{items=(await prisma.articulo.findMany({where:{id:{in:ids}}})).map((art:any)=>({name:art.nombre,code:art.sku,payload:art.codigoQR}));}if(!items.length)throw new AppError(422,'Selecciona al menos un artículo.');return pdfResponse(await labelsPdf(items),'etiquetas-imhotep.pdf',url.searchParams.get('download')==='1');}
 if(resource==='reportes'){requirePermission(a,'reportes.ver');const type=id??'inventario';const result=await readResource(a,[type==='adeudos'?'empleados':type],url.searchParams);let headers:string[]=[],rows:any[][]=[];if(type==='inventario'){headers=['Almacén','Código','Artículo','Disponible','Mínimo','Ubicación','Costo MXN'];rows=(result.data??[]).map((r:any)=>[r.almacen?.nombre,r.articulo?.sku,r.articulo?.nombre,r.cantidad,r.stockMinimo,r.ubicacionFisica,r.articulo?.costoPromedio]);}else{headers=['Folio','Tipo','Fecha','Almacén','Trabajador','Con aviso'];rows=(result.data??[]).map((r:any)=>[r.folio,r.tipo,r.fecha.toISOString(),r.almacen?.nombre,r.empleado?.nombre,r.avisoExcedido?'Sí':'No']);}if(url.searchParams.get('formato')==='pdf')return pdfResponse(await tablePdf(`Reporte de ${type} · página ${url.searchParams.get('page')??1}`,headers,rows),'reporte-imhotep.pdf',true);const cell=(v:any)=>'"'+String(v??'').replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const csv='\uFEFF'+[headers,...rows].map((r:any[])=>r.map(cell).join(',')).join('\r\n');return new Response(csv,{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':'attachment; filename="reporte-imhotep.csv"'}});}
 return output(await readResource(a,path,url.searchParams));
 }catch(e){return failure(e);}}
export async function POST(request:Request,{params}:{params:Promise<{path:string[]}>}){try{const a=await getActor();const {path}=await params;const origin=request.headers.get('origin');const host=request.headers.get('x-forwarded-host')??request.headers.get('host');if(origin&&new URL(origin).host!==host)throw new AppError(403,'La solicitud no proviene de esta aplicación.');if(a.mustChange&&path[0]!=='password')throw new AppError(403,'Cambia tu contraseña temporal antes de continuar.');
 if(path[0]==='archivos'){if(!a.permissions.includes('entregas.crear')&&!a.permissions.includes('devoluciones.crear')&&!a.permissions.includes('empleados.gestionar'))throw new AppError(403,'No tienes permiso para subir evidencias.');const form=await request.formData();const file=form.get('file');if(!(file instanceof File)||file.size>10*1024*1024||file.size===0)throw new AppError(422,'Elige una imagen de hasta 10 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new AppError(422,'Solo se permiten fotos JPG, PNG o WebP.');const buffer=Buffer.from(await file.arrayBuffer());const valid=file.type==='image/png'?buffer.subarray(1,4).toString()==='PNG':file.type==='image/jpeg'?buffer[0]===255&&buffer[1]===216:buffer.subarray(8,12).toString()==='WEBP';if(!valid)throw new AppError(422,'El contenido del archivo no corresponde a una fotografía.');const result=await storeFile(a.id,file.name,file.type,buffer);return output({id:result.id,nombre:result.nombre,hash:result.hash});}
 const result=await writeResource(a,path,await request.json());clearCache();return output(result);
 }catch(e){return failure(e);}}
