import { prisma } from './db';
import {Actor,AppError,requirePermission,warehouseWhere,scope} from './access';
import {globalRoles,canApprove} from './permissions';
import {readQr} from './qr';
const cache=new Map<string,{at:number;data:any}>();
async function cached(key:string,fn:()=>Promise<any>,ttl=30000){const item=cache.get(key);if(item&&Date.now()-item.at<ttl)return item.data;const data=await fn();if(cache.size>200)cache.clear();cache.set(key,{at:Date.now(),data});return data;}
export function clearCache(){cache.clear();}
export function employeeScope(a:Actor){if(a.role==='TRABAJADOR')return {id:a.employeeId??'none'};return ['SUPERVISOR','ALMACENISTA'].includes(a.role)?{almacenBaseId:{in:a.warehouseIds}}:{};}
export function movementScope(a:Actor,warehouse?:string|null){return a.role==='TRABAJADOR'?{empleadoId:a.employeeId??'none'}:warehouseWhere(a,warehouse);}
export function cleanEmployee(e:any,a:Actor){if(!e)return null;const {nss,curp,salarioDiario,...rest}=e;return ['RH','ADMIN','ADMIN_PRINCIPAL'].includes(a.role)?e:rest;}
async function enrichMovements(rows:any[]){const employees=await prisma.empleado.findMany({where:{id:{in:rows.map((m:any)=>m?.empleadoId).filter(Boolean)}},select:{id:true,nombre:true,apellidoPaterno:true}});const warehouses=await prisma.almacen.findMany({select:{id:true,nombre:true,clave:true}});return rows.map((m:any)=>({...m,empleado:employees.find((e:any)=>e.id===m.empleadoId),almacen:warehouses.find((w:any)=>w.id===m.almacenId)}));}
export async function assignments(a:Actor,employeeId:string){const emp=await prisma.empleado.findFirst({where:{id:employeeId,...employeeScope(a)}});if(!emp)throw new AppError(404,'No encontramos al trabajador dentro de tu alcance.');const rows=await prisma.asignacion.findMany({where:{empleadoId:employeeId,cerrada:false,saldo:{gt:0}},orderBy:{fechaEntrega:'desc'},take:100});const arts=await prisma.articulo.findMany({where:{id:{in:rows.map((r:any)=>r.articuloId)}}});return {empleado:cleanEmployee(emp,a),data:rows.map((r:any)=>({...r,articulo:arts.find((art:any)=>art.id===r.articuloId)}))};}
export async function readResource(a:Actor,path:string[],params:URLSearchParams):Promise<any>{
 const [resource,id,action]=path;const q=(params.get('q')??'').slice(0,100);const warehouse=params.get('almacenId');const page=Math.max(1,Math.min(10000,Number(params.get('page')??1)||1));const take=50,skip=(page-1)*take;const sw=warehouseWhere(a,warehouse);const query=q?{contains:q,mode:'insensitive' as const}:undefined;
 if(resource==='me')return a;
 if(resource==='bootstrap'){const almacenes=await prisma.almacen.findMany({where:{activo:true,...(globalRoles.includes(a.role)?{}:{id:{in:a.warehouseIds}})},orderBy:{creadoEn:'asc'}});const destinos=a.permissions.includes('traspasos.crear')?await prisma.almacen.findMany({where:{activo:true},select:{id:true,nombre:true,clave:true}}):[];return {almacenes,destinos,cursos:a.permissions.includes('empleados.ver')?await prisma.curso.findMany({where:{activo:true}}):[],notificaciones:await prisma.notificacion.findMany({where:{usuarioId:a.id,leida:false},take:10,orderBy:{creadoEn:'desc'}})};}
 if(resource==='dashboard'){requirePermission(a,'dashboard.ver');return cached(`dash:${a.id}:${warehouse??'all'}`,async()=>{const since=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const [metrics,summaries,alerts,risks,latest]=await Promise.all([prisma.metricaDiaria.findMany({where:{...sw,dia:{gte:since}},orderBy:{dia:'asc'}}),prisma.resumenAlmacen.findMany({where:sw}),prisma.alerta.findMany({where:{...sw,resuelta:false},orderBy:{creadoEn:'desc'},take:8}),prisma.empleado.groupBy({by:['riesgo'],where:{activo:true,...employeeScope(a)},_count:{_all:true}}),prisma.movimiento.findMany({where:sw,orderBy:{fecha:'desc'},take:6})]);const today=new Date().toISOString().slice(0,10);const daily=Array.from({length:7},(_:unknown,i:number)=>{const dia=new Date(Date.now()-(6-i)*86400000).toISOString().slice(0,10);const matches=metrics.filter((m:any)=>m.dia===dia);return {dia:dia.slice(5),entregas:matches.reduce((n:number,m:any)=>n+m.entregas,0),devoluciones:matches.reduce((n:number,m:any)=>n+m.devoluciones,0),traspasos:matches.reduce((n:number,m:any)=>n+m.traspasos,0)};});const current=metrics.filter((m:any)=>m.dia===today);return {entregas:current.reduce((n:number,m:any)=>n+m.entregas,0),devoluciones:current.reduce((n:number,m:any)=>n+m.devoluciones,0),valor:summaries.reduce((n:number,s:any)=>n+Number(s.valor),0),pendientes:summaries.reduce((n:number,s:any)=>n+Number(s.piezasPrestadas),0),alerts,risks,daily,latest:await enrichMovements(latest),actualizadoEn:new Date().toISOString()};});}
 if(resource==='operacion'){requirePermission(a,'inventario.ver');return {alerts:await prisma.alerta.findMany({where:{...sw,resuelta:false},orderBy:{creadoEn:'desc'},take:8}),latest:await enrichMovements(await prisma.movimiento.findMany({where:sw,orderBy:{fecha:'desc'},take:10})),stock:await prisma.existencia.findMany({where:{...sw,articulo:{activo:true}},include:{articulo:true},take:12,orderBy:{actualizadoEn:'desc'}}),pendientes:await cached(`pending:${a.id}:${warehouse}`,()=>prisma.solicitud.count({where:{...sw,estado:'PENDIENTE'}}))};}
 if(resource==='inventario'||resource==='articulos'){requirePermission(a,'inventario.ver');if(id){const art=await prisma.articulo.findUnique({where:{id},include:{existencias:{where:sw,include:{almacen:true}},piezas:{where:sw},variantes:true}});if(!art||!art.activo)throw new AppError(404,'Artículo no encontrado.');return art;}const tipo=params.get('tipo');const where:any={...sw,articulo:{activo:true,...(q?{OR:[{nombre:query},{sku:query},{codigoBarras:query}]}:{}),...(tipo?{tipo}: {})}};const rows=await prisma.existencia.findMany({where,include:{articulo:{include:{variantes:true}},almacen:true},orderBy:[{articulo:{creadoEn:'desc'}},{articulo:{nombre:'asc'}}],take:take+1,skip});return {data:rows.slice(0,take),hasMore:rows.length>take,page};}
 if(resource==='almacenes'){requirePermission(a,'almacenes.ver');return {data:await prisma.almacen.findMany({where:{activo:true,...(globalRoles.includes(a.role)?{}:{id:{in:a.warehouseIds}})},include:{almacenPadre:true},orderBy:{creadoEn:'asc'}})};}
 if(resource==='empleados'){requirePermission(a,'empleados.ver');if(id&&action==='asignaciones')return assignments(a,id);if(id){const e=await prisma.empleado.findFirst({where:{id,...employeeScope(a)},include:{capacitaciones:{include:{curso:true}}}});if(!e)throw new AppError(404,'Trabajador no encontrado.');return {empleado:cleanEmployee(e,a),asignaciones:(await assignments(a,id)).data,movimientos:await prisma.movimiento.findMany({where:{empleadoId:id,...movementScope(a)},take:20,orderBy:{fecha:'desc'}})};}const where:any={activo:true,...employeeScope(a),...(q?{OR:[{nombre:query},{apellidoPaterno:query},{numeroEmpleado:query},{puesto:query},{areaTrabajo:query}]}:{}),...(params.get('riesgo')?{riesgo:params.get('riesgo')}: {})};const rows=await prisma.empleado.findMany({where,orderBy:{nombre:'asc'},take:take+1,skip});return {data:rows.slice(0,take).map((e:any)=>cleanEmployee(e,a)),hasMore:rows.length>take,page};}
 if(resource==='mi-equipo'){return assignments(a,a.employeeId??'none');}
 if(resource==='piezas'){requirePermission(a,'piezas.ver');return {data:await prisma.pieza.findMany({where:{activo:true,...sw,...(q?{OR:[{codigoInterno:query},{numeroSerie:query},{articulo:{nombre:query}}]}:{})},include:{articulo:true,inspecciones:{orderBy:{fecha:'desc'},take:1},empleadoAsignado:{select:{nombre:true,apellidoPaterno:true}}},take:50,orderBy:{codigoInterno:'asc'}})};}
 if(resource==='movimientos'||resource==='documentos'){requirePermission(a,resource==='documentos'?'documentos.ver':'movimientos.ver');const where:any={...movementScope(a,warehouse),...(q?{folio:query}:{}),...(params.get('tipo')?{tipo:params.get('tipo')}:{}),...(params.get('aviso')==='true'?{avisoExcedido:true}:{}),...(params.get('desde')||params.get('hasta')?{fecha:{...(params.get('desde')?{gte:new Date(params.get('desde')!)}:{}),...(params.get('hasta')?{lte:new Date(params.get('hasta')!+'T23:59:59Z')}: {})}}:{})};if(id){const m=await prisma.movimiento.findFirst({where:{id,...movementScope(a)},include:{detalles:true,documentos:true}});if(!m)throw new AppError(404,'Movimiento no encontrado.');const arts=await prisma.articulo.findMany({where:{id:{in:m.detalles.map((d:any)=>d.articuloId)}}});return {...(await enrichMovements([m]))[0],detalles:m.detalles.map((d:any)=>({...d,articulo:arts.find((art:any)=>art.id===d.articuloId)}))};}const rows=await prisma.movimiento.findMany({where,orderBy:{fecha:'desc'},take:take+1,skip});return {data:await enrichMovements(rows.slice(0,take)),hasMore:rows.length>take,page};}
 if(resource==='kits'){requirePermission(a,'inventario.ver');return {data:await prisma.kitAlmacen.findMany({where:{...sw,activo:true},include:{articulos:{include:{articulo:true}}}})};}
 if(resource==='traspasos'){requirePermission(a,'movimientos.ver');const rows=await prisma.traspaso.findMany({where:globalRoles.includes(a.role)?{}:{OR:[{almacenOrigenId:{in:a.warehouseIds}},{almacenDestinoId:{in:a.warehouseIds}}]},orderBy:{fechaEnvio:'desc'},take:50});const details=await prisma.movimientoDetalle.findMany({where:{movimientoId:{in:rows.map((r:any)=>r.movimientoSalidaId).filter(Boolean)}}});const arts=await prisma.articulo.findMany({where:{id:{in:details.map((d:any)=>d.articuloId)}}});return {data:rows.map((r:any)=>({...r,renglones:details.filter((d:any)=>d.movimientoId===r.movimientoSalidaId).map((d:any)=>({...d,articulo:arts.find((art:any)=>art.id===d.articuloId)}))}))};}
 if(resource==='solicitudes'){requirePermission(a,'solicitudes.ver');const where:any=a.role==='TRABAJADOR'?{solicitanteId:a.id}:a.role==='COMPRAS'?{tipo:'COMPRA'}:sw;const rows=await prisma.solicitud.findMany({where,include:{renglones:true},orderBy:{creadoEn:'desc'},take:50});const arts=await prisma.articulo.findMany({where:{id:{in:rows.flatMap((r:any)=>r.renglones.map((l:any)=>l.articuloId)).filter(Boolean)}}});return {data:rows.map((r:any)=>({...r,renglones:r.renglones.map((l:any)=>({...l,articulo:arts.find((art:any)=>art.id===l.articuloId)}))}))};}
 if(resource==='usuarios'){requirePermission(a,'usuarios.ver');const users=await prisma.usuario.findMany({where:{oculto:false,...(['ADMIN_PRINCIPAL','ADMIN','RH'].includes(a.role)?{}:{OR:[{superiorId:a.id},{id:a.id}]})},select:{id:true,nombre:true,email:true,activo:true,rol:true,superiorId:true,almacenes:{include:{almacen:true}},permisos:{include:{permiso:true}}},take:100,orderBy:{creadoEn:'asc'}});const requests=await prisma.solicitudRegistroUsuario.findMany({where:{...(a.role==='RH'?{creadoPorId:a.id}:{}),estado:'PENDIENTE'},take:100});return {data:users,solicitudes:requests.filter((r:any)=>a.role==='RH'||canApprove(a.role,r.rolSolicitado))};}
 if(resource==='visor'){requirePermission(a,'visor.ver');if(!q)return {empleados:[],articulos:[],movimientos:[]};return {empleados:(await readResource(a,['empleados'],params)).data,articulos:(await readResource(a,['inventario'],params)).data,movimientos:(await readResource(a,['movimientos'],params)).data};}
 if(resource==='scan'){requirePermission(a,'inventario.ver');const raw=q;const decoded=readQr(raw);const employee=decoded?.type==='E'?await prisma.empleado.findFirst({where:{id:decoded.id,activo:true,...employeeScope(a)}}):await prisma.empleado.findFirst({where:{numeroEmpleado:raw,activo:true,...employeeScope(a)}});if(employee)return {type:'empleado',data:cleanEmployee(employee,a)};const piece=await prisma.pieza.findFirst({where:{activo:true,...sw,...(decoded?.type==='P'?{id:decoded.id}:{OR:[{codigoInterno:raw},{numeroSerie:raw}]})},include:{articulo:true}});if(piece)return {type:'pieza',data:piece};const art=await prisma.articulo.findFirst({where:{activo:true,...(decoded?.type==='A'?{id:decoded.id}:{OR:[{sku:raw},{codigoBarras:raw}]})}});if(art)return {type:'articulo',data:art};throw new AppError(404,'Código no encontrado. Revisa el código o busca por nombre.');}
 if(resource==='bajas'){requirePermission(a,'empleados.ver');const rows=await prisma.baja.findMany({where:{empleadoId:{in:(await prisma.empleado.findMany({where:employeeScope(a),select:{id:true},take:10000})).map((e:any)=>e.id)}},orderBy:{creadoEn:'desc'},take:50});const employees=await prisma.empleado.findMany({where:{id:{in:rows.map((r:any)=>r.empleadoId)}}});return {data:rows.map((r:any)=>({...r,empleado:cleanEmployee(employees.find((e:any)=>e.id===r.empleadoId),a)}))};}
 if(resource==='compras'){requirePermission(a,'compras.ver');return {requisiciones:await prisma.requisicion.findMany({include:{renglones:true},take:50,orderBy:{creadoEn:'desc'}}),ordenes:await prisma.ordenCompra.findMany({include:{pagos:true},take:50,orderBy:{fechaEmision:'desc'}}),proveedores:await prisma.proveedor.findMany({where:{activo:true},take:100})};}
 if(resource==='entradas'){requirePermission(a,'inventario.ver');return {data:await prisma.entrada.findMany({where:sw,orderBy:{creadoEn:'desc'},take:50})};}
 if(resource==='auditoria'){requirePermission(a,'auditoria.ver');return {data:await prisma.auditoria.findMany({where:q?{OR:[{accion:query},{entidadId:query}]}:{},orderBy:{fecha:'desc'},take:take+1,skip}),page};}
 throw new AppError(404,'No encontramos esta opción.');
}
