import bcrypt from 'bcryptjs';
import { randomBytes } from 'crypto';
import { prisma } from './db';
import { Actor,AppError,requirePermission } from './access';
import { canApprove,levels,nonDelegable } from './permissions';
import { transaction,Tx } from './inventory-service';
import { qr } from './qr';
async function activate(tx:Tx,row:any,approver:string){
 const temporary=randomBytes(12).toString('base64url');const role=await tx.rol.findUniqueOrThrow({where:{codigo:row.rolSolicitado}});
 let employee=await tx.empleado.findUnique({where:{numeroEmpleado:row.numeroNomina}});
 if(!employee){const id=randomBytes(12).toString('hex');const names=row.nombreCompleto.split(' ');employee=await tx.empleado.create({data:{id,numeroEmpleado:row.numeroNomina,nombre:names[0],apellidoPaterno:names.slice(1).join(' ')||'Sin apellido',puesto:row.puesto,areaTrabajo:row.area,gafeteQR:qr('E',id),almacenBaseId:row.almacenes?.[0]??null}});}
 const user=await tx.usuario.create({data:{usuario:row.email,email:row.email,nombre:row.nombreCompleto,passwordHash:await bcrypt.hash(temporary,12),rolId:role.id,empleadoId:employee.id,debeCambiarPassword:true,superiorId:approver,almacenes:{create:(row.almacenes??[]).map((id:string)=>({almacenId:id}))}}});
 await tx.solicitudRegistroUsuario.update({where:{id:row.id},data:{estado:'APROBADA',aprobadoPorId:approver,aprobadoEn:new Date()}});
 await tx.notificacion.create({data:{usuarioId:row.creadoPorId,titulo:'Registro aprobado',cuerpo:`La cuenta de ${row.nombreCompleto} está activa. Entrega la contraseña temporal de forma privada. Correo externo simulado.`,enlace:'/usuarios'}});
 await tx.auditoria.create({data:{usuarioId:approver,accion:'USUARIO_APROBADO',entidad:'Usuario',entidadId:user.id,despues:{solicitudId:row.id,creadoPorId:row.creadoPorId}}});
 return {email:user.email,temporaryPassword:temporary,mensaje:'Cuenta creada. Entrega esta contraseña temporal de forma privada. El correo está en modo simulado.'};
}
export async function requestUser(a:Actor,data:any){if(a.role!=='RH')throw new AppError(403,'Solo Recursos Humanos puede solicitar nuevas cuentas.');if(data.rolSolicitado==='ALMACENISTA'&&!data.almacenes.length)throw new AppError(422,'Asigna al menos un almacén al almacenista.');const wh=await prisma.almacen.findMany({where:{id:{in:data.almacenes},activo:true}});if(wh.length!==data.almacenes.length)throw new AppError(422,'Revisa los almacenes seleccionados.');return transaction(async(tx:Tx)=>{const row=await tx.solicitudRegistroUsuario.create({data:{...data,creadoPorId:a.id}});if(['TRABAJADOR','ALMACENISTA','COMPRAS'].includes(data.rolSolicitado))return activate(tx,row,a.id);const approvers=await tx.usuario.findMany({where:{activo:true,oculto:false,rol:{codigo:{in:['ADMIN_PRINCIPAL','ADMIN','SUPERVISOR_GENERAL']}}},include:{rol:true}});for(const user of approvers)if(canApprove(user.rol.codigo,data.rolSolicitado))await tx.notificacion.create({data:{usuarioId:user.id,titulo:'Nueva solicitud de cuenta',cuerpo:`RH solicita ${data.rolSolicitado} para ${data.nombreCompleto}.`,enlace:'/usuarios'}});return {solicitud:row,mensaje:'Solicitud enviada para aprobación. No se creó una cuenta todavía.'};});}
export async function approveUser(a:Actor,id:string,approve:boolean){requirePermission(a,'usuarios.aprobar');return transaction(async(tx:Tx)=>{const row=await tx.solicitudRegistroUsuario.findUnique({where:{id}});if(!row||row.estado!=='PENDIENTE')throw new AppError(422,'Esta solicitud ya fue atendida.');if(!canApprove(a.role,row.rolSolicitado))throw new AppError(403,'Tu rango no puede aprobar este rol.');if(approve)return activate(tx,row,a.id);await tx.solicitudRegistroUsuario.update({where:{id},data:{estado:'RECHAZADA',aprobadoPorId:a.id,aprobadoEn:new Date()}});await tx.notificacion.create({data:{usuarioId:row.creadoPorId,titulo:'Registro rechazado',cuerpo:`No se aprobó la cuenta de ${row.nombreCompleto}.`,enlace:'/usuarios'}});return {mensaje:'Solicitud rechazada.'};});}
export async function delegate(a:Actor,data:any){requirePermission(a,'permisos.delegar');if(!['ADMIN_PRINCIPAL','ADMIN','SUPERVISOR_GENERAL','SUPERVISOR'].includes(a.role))throw new AppError(403,'Este rol no puede delegar permisos.');return transaction(async(tx:Tx)=>{
 const target=await tx.usuario.findUniqueOrThrow({where:{id:data.usuarioId},include:{rol:true}});const perm=await tx.permiso.findUniqueOrThrow({where:{codigo:data.permiso}});
 if(nonDelegable.includes(data.permiso)||!perm.delegable||!a.permissions.includes(data.permiso)||(levels[target.rol.codigo]??0)>=(levels[a.role]??0))throw new AppError(403,'Solo puedes delegar tus permisos operativos a un rango inferior.');
 if(!['ADMIN_PRINCIPAL','ADMIN'].includes(a.role)){let parent=target.superiorId;let found=false;for(let n=0;n<20&&parent;n++){if(parent===a.id){found=true;break;}parent=(await tx.usuario.findUnique({where:{id:parent},select:{superiorId:true}}))?.superiorId??null;}if(!found)throw new AppError(403,'La cuenta no pertenece a tu equipo.');}
 await tx.usuarioPermiso.upsert({where:{usuarioId_permisoId:{usuarioId:target.id,permisoId:perm.id}},create:{usuarioId:target.id,permisoId:perm.id,otorgadoPorId:a.id,concedido:data.concedido,motivo:data.motivo},update:{concedido:data.concedido,otorgadoPorId:a.id,motivo:data.motivo}});
 if(!data.concedido){let parents=[target.id];for(let depth=0;depth<20&&parents.length;depth++){const delegated=await tx.usuarioPermiso.findMany({where:{otorgadoPorId:{in:parents},permisoId:perm.id,concedido:true}});for(const d of delegated){await tx.usuarioPermiso.update({where:{id:d.id},data:{concedido:false}});await tx.auditoria.create({data:{usuarioId:a.id,accion:'PERMISO_REVOCADO_CASCADA',entidad:'Usuario',entidadId:d.usuarioId}});}parents=delegated.map((d:any)=>d.usuarioId);}}
 await tx.auditoria.create({data:{usuarioId:a.id,accion:data.concedido?'PERMISO_OTORGADO':'PERMISO_REVOCADO',entidad:'Usuario',entidadId:target.id,despues:{permiso:data.permiso,motivo:data.motivo}}});return {mensaje:'Permisos guardados.'};});}
