import {z} from 'zod';
import {randomUUID} from 'crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {prisma} from './db';
import {Actor,AppError,requirePermission,scope,audit} from './access';
import {employeeScope,movementScope,assignments} from './read-service';
import {deliverySchema,returnSchema,employeeSchema,registerSchema,lineSchema} from './schemas';
import {transaction,Tx,nextFolio,evaluate,confirmDelivery,returnItems,sendTransfer,receiveTransfer,stock,metrics,updateStockAlert} from './inventory-service';
import {requestUser,approveUser,delegate} from './user-service';
import {receiptPdf,evidencePdf} from './pdf-service';
import {storeFile} from './storage';
import {qr} from './qr';
export async function writeResource(a:Actor,path:string[],body:any){const [resource,id,action]=path;
 if(resource==='entregas'&&id==='validar'){requirePermission(a,'entregas.crear');const data=deliverySchema.parse(body);scope(a,data.almacenId);const r=await evaluate(prisma as any,data);return {avisos:r.avisos,bloqueos:r.bloqueos,requiresPhoto:r.requiresPhoto};}
 if(resource==='entregas'&&id==='preparar'){requirePermission(a,'entregas.crear');const data=deliverySchema.parse(body);scope(a,data.almacenId);const r=await evaluate(prisma as any,data);if(r.bloqueos.length)throw new AppError(422,'Hay un bloqueo que requiere atención.',r.bloqueos);if(r.avisos.length&&!data.continuarConAvisos)throw new AppError(409,'Confirma los avisos antes de continuar.',r.avisos);if(r.requiresPhoto&&!data.fotoArticuloId)throw new AppError(422,'Se necesita la foto del artículo de $5,000 MXN o más.');if(!data.firmaArchivoId)throw new AppError(422,'Pide al trabajador que firme antes de continuar.');for(const f of [data.firmaArchivoId,data.fotoArticuloId].filter(Boolean)){if(!await prisma.archivo.findFirst({where:{id:f,usuarioId:a.id,contentType:{in:['image/png','image/jpeg','image/webp']}}}))throw new AppError(422,'La evidencia no pertenece a tu cuenta.');}const draft=await transaction(async(tx:Tx)=>tx.borradorEntrega.create({data:{usuarioId:a.id,almacenId:data.almacenId,empleadoId:data.empleadoId,folio:await nextFolio(tx,'VAL','GLOBAL'),datos:data}}));return draft;}
 if(resource==='entregas'&&id&&action==='confirmar'){const d=z.object({fotoFirmadaId:z.string(),tipo:z.enum(['TICKET_IMPRESO','LIBRETA'])}).parse(body);const draft=await prisma.borradorEntrega.findFirst({where:{id,usuarioId:a.id}});if(!draft)throw new AppError(404,'Borrador no encontrado.');if(draft.confirmado)return prisma.movimiento.findUnique({where:{borradorId:id}});const photo=await prisma.archivo.findFirst({where:{id:d.fotoFirmadaId,usuarioId:a.id,contentType:{in:['image/jpeg','image/png','image/webp']}}});if(!photo)throw new AppError(422,'Sube la fotografía del papel firmado.');const [evidence,receipt]=await Promise.all([evidencePdf(photo.id,draft.folio),receiptPdf(draft.folio,draft.datos,draft.creadoEn)]);const [eFile,rFile]=await Promise.all([storeFile(a.id,`${draft.folio}-evidencia.pdf`,'application/pdf',evidence),storeFile(a.id,`${draft.folio}.pdf`,'application/pdf',receipt)]);return confirmDelivery(a,id,{...d,evidenciaPdfId:eFile.id,comprobanteArchivoId:rFile.id});}
 if(resource==='devoluciones'){const data=returnSchema.parse(body);if(data.fotoRetornoId&&!await prisma.archivo.findFirst({where:{id:data.fotoRetornoId,usuarioId:a.id}}))throw new AppError(422,'La foto no pertenece a tu cuenta.');return returnItems(a,data);}
 if(resource==='traspasos'){if(id&&action==='recibir')return receiveTransfer(a,id,z.object({renglones:z.array(z.object({articuloId:z.string(),cantidad:z.coerce.number().nonnegative(),motivo:z.string().optional()}))}).parse(body).renglones);return sendTransfer(a,z.object({almacenId:z.string(),destinoId:z.string(),renglones:z.array(lineSchema).min(1).max(30)}).parse(body));}
 if(resource==='usuarios'){if(id&&action==='aprobar')return approveUser(a,id,true);if(id&&action==='rechazar')return approveUser(a,id,false);if(id&&action==='eliminar-preparar'){requirePermission(a,'usuarios.eliminar');return {token:jwt.sign({actor:a.id,target:id,ready:Date.now()+10000},process.env.AUTH_SECRET!,{expiresIn:'5m'})};}if(id&&action==='eliminar'){requirePermission(a,'usuarios.eliminar');const d=z.object({token:z.string()}).parse(body);let token:any;try{token=jwt.verify(d.token,process.env.AUTH_SECRET!);}catch{throw new AppError(422,'La confirmación venció. Vuelve a abrir el diálogo.');}if(token.actor!==a.id||token.target!==id||Date.now()<token.ready)throw new AppError(422,'Espera los diez segundos para confirmar.');return transaction(async(tx:Tx)=>{const target=await tx.usuario.findUniqueOrThrow({where:{id},include:{rol:true}});if(target.oculto||target.id===a.id||target.rol.codigo==='ADMIN_PRINCIPAL')throw new AppError(403,'No puedes eliminar esta cuenta protegida.');await tx.usuario.update({where:{id},data:{activo:false,eliminadoEn:new Date()}});await tx.auditoria.create({data:{usuarioId:a.id,accion:'ELIMINAR_LOGICO',entidad:'Usuario',entidadId:id}});return {mensaje:'La cuenta fue desactivada. El historial se conserva.'};});}if(id&&action==='reactivar'){if(a.role!=='ADMIN_PRINCIPAL')throw new AppError(403,'Solo el administrador principal puede reactivar cuentas.');await prisma.usuario.update({where:{id},data:{activo:true,eliminadoEn:null}});await audit(a,'REACTIVAR','Usuario',id);return {mensaje:'Cuenta reactivada.'};}return requestUser(a,registerSchema.parse(body));}
 if(resource==='permisos'){return delegate(a,z.object({usuarioId:z.string(),permiso:z.string(),concedido:z.boolean(),motivo:z.string().min(5)}).parse(body));}
 if(resource==='password'){const d=z.object({actual:z.string(),nueva:z.string().min(8).regex(/[A-Za-z]/).regex(/[0-9]/)}).parse(body);const user=await prisma.usuario.findUniqueOrThrow({where:{id:a.id}});if(!await bcrypt.compare(d.actual,user.passwordHash))throw new AppError(422,'La contraseña actual no es correcta.');await prisma.usuario.update({where:{id:a.id},data:{passwordHash:await bcrypt.hash(d.nueva,12),debeCambiarPassword:false}});return {mensaje:'Contraseña guardada.'};}
 if(resource==='empleados'){requirePermission(a,action==='capacitaciones'?'capacitaciones.registrar':'empleados.gestionar');if(id&&action==='capacitaciones'){const d=z.object({cursoId:z.string(),fechaCurso:z.string(),vigenciaHasta:z.string(),instructor:z.string().min(2)}).parse(body);if(new Date(d.vigenciaHasta)<=new Date(d.fechaCurso))throw new AppError(422,'La vigencia debe ser posterior al curso.');await prisma.capacitacion.create({data:{...d,empleadoId:id,fechaCurso:new Date(d.fechaCurso),vigenciaHasta:new Date(d.vigenciaHasta),registradoPorId:a.id}});await audit(a,'CAPACITACION','Empleado',id);return {mensaje:'Capacitación guardada.'};}const d=employeeSchema.parse(body);if(id){await prisma.empleado.update({where:{id},data:{...d,fechaTerminacion:d.fechaTerminacion?new Date(d.fechaTerminacion):null}});await audit(a,'ACTUALIZAR','Empleado',id);return {mensaje:'Datos guardados.'};}const eid=randomUUID();const emp=await prisma.empleado.create({data:{...d,id:eid,fechaTerminacion:d.fechaTerminacion?new Date(d.fechaTerminacion):null,gafeteQR:qr('E',eid)}});await audit(a,'CREAR','Empleado',eid);return emp;}
 if(resource==='articulos'){requirePermission(a,'articulos.gestionar');const d=z.object({nombre:z.string().min(3),sku:z.string().min(2),tipo:z.enum(['EPP','HERRAMIENTA','CONSUMIBLE','MATERIAL']),modoControl:z.enum(['SERIE','LOTE']).default('LOTE'),unidad:z.string().default('PZA'),costoPromedio:z.coerce.number().nonnegative(),esRetornable:z.boolean(),esAlturas:z.boolean().default(false),iconoLucide:z.string().default('Box'),almacenId:z.string(),stockMinimo:z.coerce.number().nonnegative().default(5),ubicacionFisica:z.string().default('')}).parse(body);scope(a,d.almacenId);const {almacenId,stockMinimo,ubicacionFisica,...art}=d;if(id){const result=await prisma.articulo.update({where:{id},data:art});await audit(a,'ACTUALIZAR','Articulo',id);return result;}const aid=randomUUID();return transaction(async(tx:Tx)=>{const created=await tx.articulo.create({data:{...art,id:aid,codigoQR:qr('A',aid),requiereInspeccion:d.esAlturas}});await tx.existencia.create({data:{articuloId:aid,almacenId,cantidad:0,stockMinimo,ubicacionFisica}});await tx.auditoria.create({data:{usuarioId:a.id,accion:'CREAR',entidad:'Articulo',entidadId:aid}});return created;});}
 if(resource==='almacenes'){requirePermission(a,'almacenes.gestionar');const d=z.object({clave:z.string().min(2).max(8),nombre:z.string().min(3),tipo:z.enum(['CENTRAL','CONTRATISTAS','AREA']),almacenPadreId:z.string().nullable().optional(),direccion:z.string().default('')}).parse(body);const created=id?await prisma.almacen.update({where:{id},data:d}):await prisma.almacen.create({data:d});await audit(a,id?'ACTUALIZAR':'CREAR','Almacen',created.id);return created;}
 if(resource==='existencias'&&id){requirePermission(a,'articulos.gestionar');const d=z.object({stockMinimo:z.coerce.number().nonnegative(),ubicacionFisica:z.string().max(150)}).parse(body);const ex=await prisma.existencia.findUniqueOrThrow({where:{id}});scope(a,ex.almacenId);const result=await prisma.existencia.update({where:{id},data:d});await audit(a,'UBICACION_MINIMO','Existencia',id);return result;}
 if(resource==='piezas'&&id){requirePermission(a,'inspecciones.registrar');const piece=await prisma.pieza.findUniqueOrThrow({where:{id}});scope(a,piece.almacenId??'');if(action==='ubicacion'){const d=z.object({pasillo:z.string(),estante:z.string(),nivel:z.string(),ubicacionNota:z.string().optional()}).parse(body);return prisma.pieza.update({where:{id},data:d});}const d=z.object({resultado:z.enum(['APTA','NO_APTA']),observaciones:z.string().min(3),dias:z.coerce.number().int().min(1).max(365),checklist:z.record(z.enum(['OK','FALLA']))}).parse(body);if(d.resultado==='APTA'&&Object.values(d.checklist).includes('FALLA'))throw new AppError(422,'No puedes aprobar una pieza con fallas.');return transaction(async(tx:Tx)=>{await tx.inspeccion.create({data:{piezaId:id,inspectorId:a.id,resultado:d.resultado,observaciones:d.observaciones,checklist:d.checklist,fotosKeys:[],vigenteHasta:new Date(Date.now()+d.dias*86400000)}});if(piece.estado==='EN_INSPECCION'&&d.resultado==='APTA'){const ex=await stock(tx,piece.almacenId!,piece.articuloId);if(Number(ex.cantidadNoDisponible)>0)await tx.existencia.update({where:{id:ex.id},data:{cantidadNoDisponible:{decrement:1},cantidad:{increment:1}}});}return tx.pieza.update({where:{id},data:{estado:d.resultado,proximaInspeccion:new Date(Date.now()+d.dias*86400000)}});});}
 if(resource==='kits'){requirePermission(a,'kits.gestionar');const d=z.object({nombre:z.string().min(3),almacenId:z.string(),articulos:z.array(z.object({articuloId:z.string(),cantidad:z.number().int().positive()})).min(1).max(30)}).parse(body);scope(a,d.almacenId);return prisma.kitAlmacen.create({data:{nombre:d.nombre,almacenId:d.almacenId,creadoPorId:a.id,articulos:{create:d.articulos}}});}
 if(resource==='solicitudes'){if(id&&['aprobar','rechazar'].includes(action)){requirePermission(a,'solicitudes.aprobar');return transaction(async(tx:Tx)=>{const s=await tx.solicitud.findUniqueOrThrow({where:{id},include:{renglones:true}});scope(a,s.almacenId);if(s.estado!=='PENDIENTE')throw new AppError(422,'Esta solicitud ya fue atendida.');if(s.tipo==='COMPRA'&&!['ADMIN','ADMIN_PRINCIPAL'].includes(a.role))throw new AppError(403,'Las compras requieren aprobación administrativa.');const decision=action==='aprobar'?'APROBADA':'RECHAZADA';await tx.autorizacion.create({data:{solicitudId:id,autorizadorId:a.id,decision,nivel:1}});if(decision==='APROBADA')for(const row of s.renglones)await tx.solicitudRenglon.update({where:{id:row.id},data:{cantidadAprobada:row.cantidad}});return tx.solicitud.update({where:{id},data:{estado:decision}});});}requirePermission(a,'solicitudes.crear');const d=z.object({almacenId:z.string(),empleadoId:z.string().optional(),tipo:z.enum(['USO','MATERIAL','COMPRA']),justificacion:z.string().min(3),renglones:z.array(lineSchema).min(1).max(30)}).parse(body);if(a.role!=='TRABAJADOR')scope(a,d.almacenId);return transaction(async(tx:Tx)=>{const wh=await tx.almacen.findUniqueOrThrow({where:{id:d.almacenId}});return tx.solicitud.create({data:{folio:await nextFolio(tx,'SO',wh.clave),almacenId:wh.id,empleadoId:a.role==='TRABAJADOR'?a.employeeId:d.empleadoId,tipo:d.tipo,justificacion:d.justificacion,solicitanteId:a.id,renglones:{create:d.renglones.map((r:any)=>({articuloId:r.articuloId,cantidad:r.cantidad}))}}});});}
 if(resource==='bajas'){if(id&&action==='cerrar'){requirePermission(a,'bajas.cerrar');const b=await prisma.baja.findUniqueOrThrow({where:{id}});const s=await assignments(a,b.empleadoId);if(s.data.length)throw new AppError(422,'Todavía hay herramientas pendientes de devolver.');await prisma.baja.update({where:{id},data:{estado:'CERRADA',cerradaEn:new Date()}});await prisma.empleado.update({where:{id:b.empleadoId},data:{estatus:'BAJA'}});await prisma.usuario.updateMany({where:{empleadoId:b.empleadoId},data:{activo:false}});await audit(a,'BAJA_CERRADA','Baja',id);return {mensaje:'Baja cerrada sin adeudos.'};}requirePermission(a,'bajas.iniciar');const d=z.object({empleadoId:z.string(),motivo:z.string().min(5)}).parse(body);const summary=await assignments(a,d.empleadoId);return transaction(async(tx:Tx)=>{const active=await tx.baja.findFirst({where:{empleadoId:d.empleadoId,estado:{in:['INICIADA','PENDIENTE_DEVOLUCION','LISTA']}}});if(active)throw new AppError(422,'Ya existe un proceso de baja para este trabajador.');await tx.empleado.update({where:{id:d.empleadoId},data:{estatus:'EN_BAJA'}});return tx.baja.create({data:{folio:await nextFolio(tx,'BJ','RH'),empleadoId:d.empleadoId,motivo:d.motivo,iniciadaPorId:a.id,estado:summary.data.length?'PENDIENTE_DEVOLUCION':'LISTA'}});});}
 if(resource==='entradas'){if(id&&action==='autorizar'){requirePermission(a,'entradas.autorizar');return transaction(async(tx:Tx)=>{const e=await tx.entrada.findUniqueOrThrow({where:{id}});scope(a,e.almacenId);if(e.estado!=='PENDIENTE')throw new AppError(422,'Esta entrada ya fue atendida.');const wh=await tx.almacen.findUniqueOrThrow({where:{id:e.almacenId}});const m=await tx.movimiento.create({data:{folio:await nextFolio(tx,'EN',wh.clave),tipo:'ENTRADA_COMPRA',almacenId:wh.id,usuarioId:a.id}});for(const l of e.renglones as any[]){const art=await tx.articulo.findUniqueOrThrow({where:{id:l.articuloId}});if(art.modoControl==='SERIE')throw new AppError(422,'Registra las series de las piezas antes de recibir este artículo.');const total=await tx.existencia.aggregate({where:{articuloId:art.id},_sum:{cantidad:true}});const amount=Number(total._sum.cantidad??0);const cost=(amount*Number(art.costoPromedio)+l.cantidad*l.costoUnitario)/(amount+l.cantidad);await tx.articulo.update({where:{id:art.id},data:{costoPromedio:cost,ultimoCosto:l.costoUnitario}});const ex=await stock(tx,wh.id,art.id);const u=await tx.existencia.update({where:{id:ex.id},data:{cantidad:{increment:l.cantidad}}});await tx.movimientoDetalle.create({data:{movimientoId:m.id,articuloId:art.id,cantidad:l.cantidad,costoUnitario:l.costoUnitario,saldoAlmacenDespues:u.cantidad}});await updateStockAlert(tx,u,art.nombre);}return tx.entrada.update({where:{id},data:{estado:'AUTORIZADA',autorizadaPorId:a.id,autorizadaEn:new Date(),movimientoId:m.id}});});}requirePermission(a,'entradas.registrar');const d=z.object({almacenId:z.string(),facturaNumero:z.string().optional(),renglones:z.array(z.object({articuloId:z.string(),cantidad:z.coerce.number().positive(),costoUnitario:z.coerce.number().nonnegative()})).min(1).max(30)}).parse(body);scope(a,d.almacenId);return transaction(async(tx:Tx)=>tx.entrada.create({data:{...d,folio:await nextFolio(tx,'EP',d.almacenId),registradaPorId:a.id}}));}
 if(resource==='compras'){requirePermission(a,'compras.gestionar');if(id&&action==='pago'){const d=z.object({monto:z.coerce.number().positive(),metodo:z.string().min(2),referencia:z.string().min(2)}).parse(body);return transaction(async(tx:Tx)=>{const order=await tx.ordenCompra.findUniqueOrThrow({where:{id},include:{pagos:true}});const paid=order.pagos.reduce((n:number,p:any)=>n+Number(p.monto),0);if(paid+d.monto>Number(order.total))throw new AppError(422,'El pago supera el saldo de la orden.');await tx.pago.create({data:{ordenCompraId:id,...d,fecha:new Date(),registradoPorId:a.id}});return tx.ordenCompra.update({where:{id},data:{estadoPago:paid+d.monto>=Number(order.total)?'PAGADO':'PARCIAL'}});});}const d=z.object({proveedorId:z.string(),descripcion:z.string().min(3),cantidad:z.coerce.number().positive(),precio:z.coerce.number().nonnegative()}).parse(body);return transaction(async(tx:Tx)=>{const sub=d.cantidad*d.precio;return tx.ordenCompra.create({data:{folio:await nextFolio(tx,'OC','COM'),proveedorId:d.proveedorId,subtotal:sub,iva:sub*.16,total:sub*1.16,creadoPorId:a.id,renglones:[d]}});});}
 if(resource==='notificaciones'&&id){await prisma.notificacion.updateMany({where:{id,usuarioId:a.id},data:{leida:true}});return {ok:true};}
 if(resource==='whatsapp'&&id){requirePermission(a,'entregas.crear');const m=await prisma.movimiento.findFirst({where:{id,...movementScope(a)}});if(!m)throw new AppError(404,'No encontramos el comprobante.');await audit(a,'WHATSAPP_SIMULADO','Movimiento',id);return {mensaje:'Envío simulado registrado. No se envió ningún mensaje real.'};}
 if(resource==='portal'){requirePermission(a,'entregas.crear');const d=z.object({empleadoId:z.string()}).parse(body);await assignments(a,d.empleadoId);return {token:jwt.sign({empleadoId:d.empleadoId,purpose:'portal'},process.env.AUTH_SECRET!,{expiresIn:'24h'})};}
 throw new AppError(404,'Esta acción no está disponible.');
}
