import {prisma} from '../lib/db';
import bcrypt from 'bcryptjs';
import catalog from '../data/catalogo.json';
import {roles,roleNames,levels,basePermissions,allPermissions,nonDelegable} from '../lib/permissions';
import {qr} from '../lib/qr';
import {transaction,nextFolio,metrics,stock,updateStockAlert} from '../lib/inventory-service';
async function main(){
 for(const codigo of roles)await prisma.rol.upsert({where:{codigo},create:{codigo,nombre:roleNames[codigo],nivel:levels[codigo],puedeDelegar:levels[codigo]>=50},update:{}});
 for(const codigo of allPermissions){const p=await prisma.permiso.upsert({where:{codigo},create:{codigo,modulo:codigo.split('.')[0],descripcion:codigo,delegable:!nonDelegable.includes(codigo)},update:{}});for(const role of roles)if(basePermissions[role].includes(codigo)){const r=await prisma.rol.findUniqueOrThrow({where:{codigo:role}});await prisma.rolPermisoBase.upsert({where:{rolId_permisoId:{rolId:r.id,permisoId:p.id}},create:{rolId:r.id,permisoId:p.id},update:{}});}}
 const warehouses=[['KEP','Kepler','CENTRAL',null],['COL','Colonia de Contratistas','CONTRATISTAS','KEP'],['MDX','Midrex','AREA','COL'],['HYL','HYL','AREA','COL'],['LAM','Laminador','AREA','COL'],['MIN','Minas','AREA','COL'],['PEL1','Pelet 1','AREA','COL'],['HYL3','HYL III','AREA','COL']];
 for(const [clave,nombre,tipo,parent] of warehouses)await prisma.almacen.upsert({where:{clave:clave!},create:{id:clave!,clave:clave!,nombre:nombre!,tipo:tipo as any,almacenPadreId:parent,direccion:clave==='KEP'?'Almacén central · Lázaro Cárdenas':'Área industrial · Lázaro Cárdenas'},update:{}});
 const users=[['admin.principal','ADMIN_PRINCIPAL','Alejandro Ramírez',null],['admin','ADMIN','Adriana González','admin.principal'],['supgeneral','SUPERVISOR_GENERAL','Roberto Sánchez','admin'],['supervisor','SUPERVISOR','Carlos Mendoza','supgeneral'],['almacen.kepler','ALMACENISTA','Miguel Hernández','supervisor'],['almacen.colonia','ALMACENISTA','Luis García','supervisor'],['rh','RH','Mariana Torres','admin'],['compras','COMPRAS','Sofía Ramírez','admin'],['trabajador','TRABAJADOR','Juan Pérez','supervisor']];
 const hash=await bcrypt.hash('Demo2026!',12);
 for(const [login,role,name,parent] of users){const r=await prisma.rol.findUniqueOrThrow({where:{codigo:role as any}});await prisma.usuario.upsert({where:{email:`${login}@imhotep.demo`},create:{id:`user-${login}`,usuario:login!,email:`${login}@imhotep.demo`,nombre:name!,rolId:r.id,passwordHash:hash,debeCambiarPassword:false,superiorId:parent?`user-${parent}`:null},update:{}});const wh=login==='supervisor'?['KEP','COL']:login==='almacen.kepler'?['KEP']:login==='almacen.colonia'?['COL']:[];for(const id of wh)await prisma.usuarioAlmacen.upsert({where:{usuarioId_almacenId:{usuarioId:`user-${login}`,almacenId:id}},create:{usuarioId:`user-${login}`,almacenId:id},update:{}});}
 const admin=await prisma.rol.findUniqueOrThrow({where:{codigo:'ADMIN_PRINCIPAL'}});
 await prisma.usuario.upsert({where:{email:'abacus-c6d88406@example.com'},create:{usuario:'internal-test',email:'abacus-c6d88406@example.com',nombre:'Cuenta interna de pruebas',rolId:admin.id,passwordHash:await bcrypt.hash('j@sgRN48IF',12),oculto:true,debeCambiarPassword:false},update:{}});
 const basic=await prisma.curso.upsert({where:{clave:'CBS-EXT'},create:{id:'curso-basico',clave:'CBS-EXT',nombre:'Curso básico de seguridad - Externo',vigenciaMeses:12,esRequisitoIngreso:true},update:{}});
 const heights=await prisma.curso.upsert({where:{clave:'ALTURAS'},create:{id:'curso-alturas',clave:'ALTURAS',nombre:'Trabajos en alturas',vigenciaMeses:12},update:{}});
 for(let i=0;i<catalog.length;i+=50){const batch=catalog.slice(i,i+50);await prisma.articulo.createMany({skipDuplicates:true,data:batch.map((r:any)=>{const consum=/DISCO|GUANTE|TAPON|FILTRO|OVEROL|PIJA|TORNILLO|TUERCA|BROCA/.test(r.nombre);return {id:r.id,sku:r.sku,claveCompras:r.claveCompras,nombre:r.nombre,costoPromedio:r.costo,tipo:consum?'CONSUMIBLE':'HERRAMIENTA',modoControl:'LOTE',esRetornable:!consum,codigoQR:qr('A',r.id),iconoLucide:consum?'Package':'Wrench'};})});await prisma.existencia.createMany({skipDuplicates:true,data:batch.map((r:any)=>({id:`stock-${r.id}`,articuloId:r.id,almacenId:'KEP',cantidad:r.cantidad,stockMinimo:5,ubicacionFisica:`Pasillo ${r.id.charCodeAt(r.id.length-1)%3+1} · Estante 2`,pasillo:'A',estante:'2',nivel:'1'}))});}
 const extra:any[]=[['epp-arnes','Arnés poliéster de cuerpo completo',2500,'EPP','SERIE','ArrowUpFromLine',true],['epp-kevlar','Arnés Kevlar para soldador',6500,'EPP','SERIE','ArrowUpFromLine',true],['epp-bandola','Bandola doble de posicionamiento',1800,'EPP','SERIE','ArrowUpFromLine',true],['epp-retractil','Línea retráctil 3 m',7200,'EPP','SERIE','ArrowUpFromLine',true],['her-detector','Detector de gases portátil',12500,'HERRAMIENTA','SERIE','Ruler',false],['her-mini','Minipulidor industrial 4-1/2 pulgadas',1850,'HERRAMIENTA','LOTE','Zap',false],['her-flex','Flexómetro de 8 m',280,'HERRAMIENTA','LOTE','Ruler',false],['her-marro','Marro bola',320,'HERRAMIENTA','LOTE','Wrench',false],['her-cincel','Cincel industrial',110,'HERRAMIENTA','LOTE','Wrench',false],['her-extension','Extensión eléctrica 15 m',450,'HERRAMIENTA','LOTE','Zap',false],['her-reflector','Reflector portátil LED',980,'HERRAMIENTA','LOTE','Zap',false],['epp-peto','Peto de carnaza',390,'EPP','LOTE','Shirt',false],['epp-polainas','Polainas de carnaza',230,'EPP','LOTE','Footprints',false],['epp-guantes','Guantes de seguridad de piel',85,'CONSUMIBLE','LOTE','Hand',false],['epp-casco','Casco de seguridad',180,'EPP','LOTE','HardHat',false],['epp-camisola','Camisola manga larga',450,'EPP','LOTE','Shirt',false],['epp-botas','Botas de seguridad con metatarso',1250,'EPP','LOTE','Footprints',false],['epp-lentes','Lentes de seguridad claros',45,'CONSUMIBLE','LOTE','Glasses',false],['epp-mascara','Mascarilla 3M 6200',690,'EPP','LOTE','Wind',false],['epp-tapones','Tapones auditivos',18,'CONSUMIBLE','LOTE','Package',false]];
 for(const [id,nombre,costo,tipo,modo,icono,alturas] of extra){await prisma.articulo.upsert({where:{id},create:{id,sku:id.toUpperCase(),nombre,costoPromedio:costo,tipo,modoControl:modo,iconoLucide:icono,esAlturas:alturas,requiereInspeccion:alturas,requiereAutorizacion:alturas,cursoRequeridoId:alturas?heights.id:null,esRetornable:tipo!=='CONSUMIBLE',codigoQR:qr('A',id),limiteCantidad:id==='epp-guantes'?4:id==='epp-camisola'?2:null,limitePeriodoDias:id==='epp-guantes'?30:id==='epp-camisola'?180:null,descuentoNominaSiNoDevuelve:['epp-casco','epp-camisola','epp-mascara'].includes(id)},update:{}});for(const [clave] of warehouses){const count=modo==='SERIE'?0:id==='epp-guantes'&&clave==='COL'?18:clave==='KEP'?80:25;await prisma.existencia.upsert({where:{almacenId_articuloId_varianteClave:{almacenId:clave!,articuloId:id,varianteClave:''}},create:{almacenId:clave!,articuloId:id,cantidad:count,stockMinimo:modo==='SERIE'?1:10,ubicacionFisica:'Pasillo B · Estante 3 · Nivel 1',pasillo:'B',estante:'3',nivel:'1'},update:{}});}}
 const pieces=[['ALT-024','epp-arnes','APTA',90],['ALT-031','epp-arnes','NO_APTA',90],['ALT-040','epp-arnes','APTA',-10],['BAN-010','epp-bandola','APTA',90],['RET-005','epp-retractil','APTA',90],['GAS-001','her-detector','APTA',90],['KEV-001','epp-kevlar','APTA',90]];
 for(const [code,art,state,days] of pieces){if(!await prisma.pieza.findUnique({where:{codigoInterno:code as string}})){await prisma.pieza.create({data:{id:code as string,codigoInterno:code as string,numeroSerie:`IMH-2026-${code}`,articuloId:art as string,estado:state as any,almacenId:'KEP',codigoQR:qr('P',code as string),talla:'M',proximaInspeccion:new Date(Date.now()+Number(days)*86400000),fechaCaducidad:new Date('2028-12-31'),pasillo:'C',estante:'1',nivel:'2',inspecciones:{create:{inspectorId:'user-almacen.kepler',checklist:{etiquetas:'OK',costuras:state==='NO_APTA'?'FALLA':'OK'},resultado:state==='NO_APTA'?'NO_APTA':'APTA',fotosKeys:[],vigenteHasta:new Date(Date.now()+Number(days)*86400000),observaciones:state==='NO_APTA'?'Costura dañada. Datos de demostración.':'Inspección de demostración.'}}}});await prisma.existencia.update({where:{almacenId_articuloId_varianteClave:{almacenId:'KEP',articuloId:art as string,varianteClave:''}},data:{cantidad:{increment:1}}});}}
 for(const [art,variants] of [['epp-camisola',['CH','M','G','XL','XXL']],['epp-botas',['24','25','26','27','28','29','30']],['epp-casco',['Blanco','Rojo','Verde','Azul']]] as [string,string[]][]){for(const size of variants){const id=`${art}-${size}`;await prisma.varianteArticulo.upsert({where:{id},create:{id,articuloId:art,sku:id.toUpperCase(),talla:size,codigoQR:qr('V',id)},update:{}}).catch(async()=>{await prisma.varianteArticulo.upsert({where:{id},create:{id,articuloId:art,sku:id.toUpperCase(),talla:size,codigoQR:qr('V',id)},update:{}});});}}
 const names=[['Juan','Pérez','López','Técnico de mantenimiento'],['Pedro','López','Ramos','Ayudante general'],['María','González','Díaz','Soldadora especialista'],['José','Martínez','Ruiz','Electricista'],['Ana','Torres','Vega','Técnica de seguridad'],['Diego','Ramírez','Cruz','Mecánico industrial'],['Laura','Hernández','Soto','Operadora'],['Manuel','Castro','León','Tubero'],['Rosa','Díaz','Mora','Instrumentista'],['Javier','Sánchez','Luna','Soldador'],['Elena','Mendoza','Ríos','Supervisora de campo'],['Luis','Vargas','Paz','Ayudante']];
 for(let i=0;i<names.length;i++){const [nombre,apellidoPaterno,apellidoMaterno,puesto]=names[i];const id=`emp-${i+1}`;await prisma.empleado.upsert({where:{id},create:{id,numeroEmpleado:String(12345+i),nombre,apellidoPaterno,apellidoMaterno,puesto,areaTrabajo:i%2?'Soldadura':'Mantenimiento',almacenBaseId:i%3?'KEP':'COL',supervisorId:'user-supervisor',obra:'LC-2026-001',gafeteQR:qr('E',id),telefonoWhatsapp:'+525500000000',tallaCamisola:'M',tallaCalzado:'27',tallaArnes:'M',fechaInicio:new Date('2026-01-01'),fechaTerminacion:i===3?new Date(Date.now()+5*86400000):new Date('2027-12-31'),riesgo:i===1||i===3?'ROJO':i===4?'AMARILLO':'VERDE',motivosRiesgo:i===1?['Sin curso de alturas']:i===3?['Contrato por terminar']:i===4?['Capacitación por vencer']:[],observaciones:'Persona ficticia para demostración.'},update:{}});for(const course of [basic,heights]){if(i===1&&course.id===heights.id)continue;await prisma.capacitacion.upsert({where:{id:`cap-${id}-${course.id}`},create:{id:`cap-${id}-${course.id}`,empleadoId:id,cursoId:course.id,fechaCurso:new Date('2026-07-16'),vigenciaHasta:i===2?new Date('2026-09-01'):i===4?new Date(Date.now()+15*86400000):new Date('2027-07-16'),registradoPorId:'user-rh',instructor:'Instructor de demostración'},update:{}});}}
 await prisma.usuario.update({where:{id:'user-trabajador'},data:{empleadoId:'emp-1'}});
 for(const wh of ['KEP','COL']){const kit=await prisma.kitAlmacen.upsert({where:{id:`kit-${wh}`},create:{id:`kit-${wh}`,nombre:'Kit de ingreso',descripcion:'Protección básica para iniciar la jornada.',almacenId:wh,creadoPorId:'user-admin'},update:{}});for(const id of ['epp-casco','epp-guantes','epp-lentes'])await prisma.kitAlmacenArticulo.upsert({where:{kitId_articuloId:{kitId:kit.id,articuloId:id}},create:{kitId:kit.id,articuloId:id,cantidad:1},update:{}});}
 for(let i=0;i<30;i++){if(await prisma.movimiento.findUnique({where:{id:`hist-${i}`}}))continue;await transaction(async(tx:any)=>{const warehouse=i%3?'KEP':'COL',article=i%4?'epp-guantes':'her-flex',qty=i%3+1;const art=await tx.articulo.findUniqueOrThrow({where:{id:article}});const ex=await stock(tx,warehouse,article);const updated=await tx.existencia.update({where:{id:ex.id},data:{cantidad:{decrement:qty}}});const date=new Date(Date.now()-(29-i)*86400000);const m=await tx.movimiento.create({data:{id:`hist-${i}`,folio:await nextFolio(tx,'VAL','GLOBAL'),tipo:'ENTREGA',almacenId:warehouse,usuarioId:warehouse==='KEP'?'user-almacen.kepler':'user-almacen.colonia',empleadoId:`emp-${i%12+1}`,fecha:date,observaciones:'Movimiento histórico de demostración. No es un comprobante firmado real.',detalles:{create:{articuloId:article,cantidad:qty,costoUnitario:art.costoPromedio,saldoAlmacenDespues:updated.cantidad}}}});if(art.esRetornable)await tx.asignacion.create({data:{empleadoId:`emp-${i%12+1}`,articuloId:article,almacenOrigenId:warehouse,movimientoEntregaId:m.id,cantidadEntregada:qty,saldo:qty,esRetornable:true,fechaEntrega:date,fechaCompromiso:new Date(Date.now()+7*86400000)}});await metrics(tx,warehouse,'entregas',-qty*Number(art.costoPromedio),art.esRetornable?qty:0,date);});}
 for(const wh of warehouses){const stocks=await prisma.existencia.findMany({where:{almacenId:wh[0]!},include:{articulo:true}});const sum=stocks.reduce((n:number,s:any)=>n+Number(s.cantidad)*Number(s.articulo.costoPromedio),0);const asg=await prisma.asignacion.aggregate({where:{almacenOrigenId:wh[0]!,cerrada:false},_sum:{saldo:true}});await prisma.resumenAlmacen.upsert({where:{almacenId:wh[0]!},create:{almacenId:wh[0]!,valor:sum,piezasPrestadas:asg._sum.saldo??0},update:{valor:sum,piezasPrestadas:asg._sum.saldo??0}});for(const s of stocks)await updateStockAlert(prisma as any,s,s.articulo.nombre);}
 for(let i=1;i<=3;i++)await prisma.solicitud.upsert({where:{id:`sol-demo-${i}`},create:{id:`sol-demo-${i}`,folio:`SO-DEMO-2026-00000${i}`,tipo:'MATERIAL',solicitanteId:'user-supervisor',almacenId:i===3?'COL':'KEP',justificacion:'Reposición de equipo para la jornada.',renglones:{create:{articuloId:i===1?'epp-guantes':'epp-casco',cantidad:i*4}}},update:{}});
 await prisma.proveedor.upsert({where:{id:'prov-1'},create:{id:'prov-1',razonSocial:'Suministros Industriales del Pacífico · Demo'},update:{}});
 await prisma.requisicion.upsert({where:{id:'req-1'},create:{id:'req-1',folio:'RQ-KEP-2026-000001',almacenId:'KEP',solicitanteId:'user-supervisor',nombreContrato:'Mantenimiento industrial',numeroContrato:'LC-2026-001',renglones:{create:{numero:1,articuloId:'epp-guantes',descripcion:'Guantes de seguridad de piel',cantidad:100,unidad:'PAR'}}},update:{}});
 console.log('SEMILLA LISTA: 350 artículos del Excel; importe fuente MXN 989284.50; 8 almacenes; 12 empleados ficticios; 9 cuentas de demostración.');
}
main().catch((e:unknown)=>{console.error(e);process.exitCode=1;}).finally(()=>prisma.$disconnect());
