'use client';
import {useEffect,useState,useRef} from 'react';
import {X,Search,ChevronLeft,ChevronRight,Package,AlertCircle,RefreshCw,Check,Box,Wrench,Zap,HardHat,Hand,Footprints,Shirt,ArrowUpFromLine,Glasses,Wind,Ruler,Loader2} from 'lucide-react';
import {toast} from 'sonner';
export const money=(v:any)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:2}).format(Number(v??0));
export const date=(v:any)=>v?new Date(v).toLocaleDateString('es-MX',{timeZone:'America/Monterrey',day:'2-digit',month:'short',year:'numeric'}):'—';
export async function api(path:string,body?:any){try{const response=await fetch('/api/v1/'+path,{...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'})});const data=await response.json();if(!response.ok)throw new Error(data?.error?.mensaje??'No se pudo completar la operación.');return data;}catch(e:any){console.error(e);throw e;}}
export function useData(path:string){const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);useEffect(()=>{let active=true;setLoading(true);setError('');api(path).then((d:any)=>{if(active)setData(d);}).catch((e:any)=>{if(active)setError(e?.message??'No se pudo cargar.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false};},[path,version]);return {data,error,loading,reload:()=>setVersion((n:number)=>n+1)};}
export function ArticleIcon({name,size=21}:{name?:string;size?:number}){const icons:Record<string,any>={Box,Wrench,Zap,HardHat,Hand,Footprints,Shirt,ArrowUpFromLine,Glasses,Wind,Ruler,Package};const Icon=icons?.[name??'Box']??Box;return <Icon size={size}/>;}
export function Badge({value}:{value:any}){const v=String(value??'');const green=['APTA','ACTIVO','APROBADA','RECIBIDO','VERDE','PAGADO','AUTORIZADA','VIGENTE','BUENO'];const red=['NO_APTA','ROJO','BAJA','RECHAZADA','PERDIDO','CANCELADO'];const labels:Record<string,string>={VERDE:'En orden',AMARILLO:'Por vencer',ROJO:'Revisar',NO_APTA:'No apta',EN_INSPECCION:'En inspección',EN_REPARACION:'En reparación',EN_TRANSITO:'En tránsito',APROBADA:'Aprobada',APTA:'Apta',ENTREGA:'Entrega',DEVOLUCION:'Devolución',TRASPASO_SALIDA:'Traspaso de salida',TRASPASO_ENTRADA:'Traspaso recibido',PENDIENTE_DEVOLUCION:'Pendiente de devolución',LISTA:'Sin pendientes',VIGENTE:'Registrado',CONSUMIBLE:'Consumible',HERRAMIENTA:'Herramienta',EPP:'EPP',LOTE:'Por cantidad',SERIE:'Por pieza'};return <span className={`badge ${green.includes(v)?'badge-green':red.includes(v)?'badge-red':['PENDIENTE','AMARILLO','EN_BAJA','EN_TRANSITO','EN_INSPECCION','EN_REPARACION'].includes(v)?'badge-amber':''}`}><span className="h-1.5 w-1.5 rounded-full bg-current"/>{labels?.[v]??v.replaceAll('_',' ').toLowerCase()}</span>;}
export function Empty({text='No hay registros que coincidan.'}:{text?:string}){return <div className="py-14 text-center text-muted-foreground"><Package size={36} className="mx-auto mb-3 opacity-40"/><p>{text}</p></div>;}
export function LoadState({loading,error,retry,children}:{loading:boolean;error:string;retry:()=>void;children:React.ReactNode}){return loading?<div className="panel p-8 space-y-4 animate-pulse"><div className="h-6 bg-muted rounded w-1/3"/><div className="h-16 bg-muted/60 rounded"/><div className="h-16 bg-muted/60 rounded"/></div>:error?<div role="alert" className="panel p-8"><AlertCircle className="text-destructive mb-3"/><p className="mb-4">{error}</p><button className="btn" onClick={retry}><RefreshCw size={18}/>Intentar de nuevo</button></div>:<>{children}</>;}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{ref.current?.focus();const h=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input,select,textarea,a[href]');const first=els?.[0],last=els?.[(els?.length??1)-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',h);return()=>document.removeEventListener('keydown',h);},[onClose]);return <div className="modal-bg" onClick={(e:React.MouseEvent)=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label={title}><div className="flex justify-between items-center gap-4 mb-6"><h2 className="text-xl font-semibold">{title}</h2><button className="btn btn-secondary p-3" aria-label="Cerrar" onClick={onClose}><X size={20}/></button></div>{children}</div></div>;}
export function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="block mb-2 text-sm font-medium">{label}</span>{children}</label>;}
export function SearchInput({value,onChange,placeholder='Buscar por nombre o código…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="relative flex-1 min-w-[180px]"><Search size={18} className="absolute left-3.5 top-4 text-muted-foreground"/><input aria-label={placeholder} className="pl-11" value={value} onChange={(e:React.ChangeEvent<HTMLInputElement>)=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
export function Pagination({page,more,onPage}:{page:number;more:boolean;onPage:(n:number)=>void}){return <div className="flex items-center justify-between p-4 text-sm text-muted-foreground"><span>Página {page} · Hasta 50 registros</span><div className="flex gap-2"><button aria-label="Página anterior" disabled={page<=1} onClick={()=>onPage(page-1)} className="btn btn-secondary"><ChevronLeft size={18}/></button><button aria-label="Página siguiente" disabled={!more} onClick={()=>onPage(page+1)} className="btn btn-secondary"><ChevronRight size={18}/></button></div></div>;}
export function SaveButton({busy,label='Guardar'}:{busy:boolean;label?:string}){return <button type="submit" disabled={busy} className="btn btn-blue">{busy?<Loader2 size={18}/>:<Check size={18}/>} {busy?'Guardando…':label}</button>;}
export async function notifyAction(fn:()=>Promise<any>,reload?:()=>void){try{const result=await fn();toast.success(result?.mensaje??'Listo. Guardado correctamente.');reload?.();return result;}catch(e:any){toast.error(e?.message??'No se pudo guardar. Intenta de nuevo.');return null;}}
